

CREATE TABLE PRODUCT
(
 
   PRODUCTID     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   NAME          VARCHAR(20) NOT NULL,
   CATEGORY      VARCHAR(20) NOT NULL,
   DESCRIPTION   VARCHAR(250) NOT NULL,
   IMAGEURI      VARCHAR(40) NOT NULL,
   PRICE         DECIMAL(10,2),
    
   
   CONSTRAINT  PK_PRODUCT  PRIMARY KEY(PRODUCTID)
);